import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='background-color-gradient '
      >
        <div className="fixed z-40 ">
          <Header/>
        </div>
        {children}
        <div className="bg-[#272727] text-white">
          <Footer/>
        </div>
      </body>
    </html>
  );
}
